export const location = [
    {   id: 1,
        city: 'Bratislava',
        path: 'bratislava',
        country: 'Slovakia',
        short_country: 'sk',
        temp: 0,
    },
    {
        id: 2,
        city: 'Humenné',
        path: 'humenne',
        country: 'Slovakia',
        short_country: 'sk',
        temp: 0,
    },
    {   id: 3,
        city: 'Koromľa',
        path: 'sobrance',
        country: 'Slovakia',
        short_country: 'sk',
        temp: 0,
    },
    {
        id: 4,
        city: 'Košice',
        path: 'kosice',
        country: 'Slovakia',
        short_country: 'sk',
        temp: 0,
    },
    {
        id: 5,
        city: 'Michalovce',
        path: 'michalovce',
        country: 'Slovakia',
        short_country: 'sk',
        temp: 0,
    },
    {
        id: 6,
        city: 'Sobrance',
        path: 'sobrance',
        country: 'Slovakia',
        short_country: 'sk',
        temp: 0,
    },

]